"Hey buddy! Wake up! Can ya hear me in there?"/???
"...What? Where am I?"/Calvin
"You're in a prison cell on our spaceship."/???
"What, do ya not remember anything?"/???
"..."/Calvin
"Come on, get up already. You remember how to use your legs, right?"/???
"Oh, and by the way, call me Abric."/Abric
"You're gonna see me pretty often from now on, so it's better we get friendly..."/Abric
"...or somethin like that."/Abric